# Generated by Django 3.0.4 on 2020-03-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.FloatField(max_length=50)),
                ('last_evaluation', models.FloatField(max_length=50)),
                ('number_project', models.IntegerField()),
                ('average_montly_hours', models.IntegerField()),
                ('time_spend_company', models.IntegerField()),
                ('Work_accident', models.IntegerField()),
                ('left', models.IntegerField(blank=True, null=True)),
                ('promotion_last_5years', models.IntegerField()),
                ('sales', models.CharField(blank=True, max_length=10, null=True)),
                ('salary', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
