# Generated by Django 3.0.4 on 2020-03-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrpred', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titanic',
            new_name='Attrition',
        ),
    ]
